export const SET_HIDE_ZERO_GAME_PLAYERS = "SET_HIDE_ZERO_GAME_PLAYERS";
export type SET_HIDE_ZERO_GAME_PLAYERS_TYPE = typeof SET_HIDE_ZERO_GAME_PLAYERS;

export const SET_SHOW_CARDS = "SET_SHOW_CARDS";
export type SET_SHOW_CARDS_TYPE = typeof SET_SHOW_CARDS;

export const SET_DISABLE_MUSIC = "SET_DISABLE_MUSIC";
export type SET_DISABLE_MUSIC_TYPE = typeof SET_DISABLE_MUSIC;

export const SET_USERNAME = "SET_USERNAME";
export type SET_USERNAME_TYPE = typeof SET_USERNAME;
