export const SET_HIDE_ZERO_GAME_PLAYERS = "SET_HIDE_ZERO_GAME_PLAYERS";
export type SET_HIDE_ZERO_GAME_PLAYERS_TYPE = typeof SET_HIDE_ZERO_GAME_PLAYERS;

export const SET_SHOW_CARDS = "SET_SHOW_CARDS";
export type SET_SHOW_CARDS_TYPE = typeof SET_SHOW_CARDS;
